from ClassBot import FileCheck

path = FileCheck.FileCheck("./image")
accept = FileCheck.FileCheck(r"image\accept.png")
battle1 = FileCheck.FileCheck(r"image\battle1.png")
battle2 = FileCheck.FileCheck(r"image\battle2.png")
sconfitta = FileCheck.FileCheck(r"image\sconfitta.png")
chiudi = FileCheck.FileCheck(r"image\chiudi.png")
cimento = FileCheck.FileCheck(r"image\cimento.png")
cittadina = FileCheck.FileCheck(r"image\cittadina.png")
close = FileCheck.FileCheck(r"image\close.png")
entra = FileCheck.FileCheck(r"image\entra.png")
fine = FileCheck.FileCheck(r"image\fine.png")
gvg = FileCheck.FileCheck(r"image\gvg.png")
invasione = FileCheck.FileCheck(r"image\invasione.png")
no = FileCheck.FileCheck(r"image\no.png")
noshard = FileCheck.FileCheck(r"image\noshard.png")
ohno = FileCheck.FileCheck(r"image\ohno.png")
play = FileCheck.FileCheck(r"image\play.png")
prove = FileCheck.FileCheck(r"image\prove.png")
pvp = FileCheck.FileCheck(r"image\pvp.png")
pvpvick =FileCheck.FileCheck(r"image\pvpvick.png")
quest = FileCheck.FileCheck(r"image\quest.png")
rerun = FileCheck.FileCheck(r"image\rerun.png")
startraid = FileCheck.FileCheck(r"image\startraid.png")

def controllotot():
    path.CheckPath()
    accept.CheckImage()
    battle1.CheckImage()
    battle2.CheckImage()
    sconfitta.CheckImage()
    chiudi.CheckImage()
    cimento.CheckImage()
    cittadina.CheckImage()
    close.CheckImage()
    entra.CheckImage()
    fine.CheckImage()
    gvg.CheckImage()
    invasione.CheckImage()
    no.CheckImage()
    noshard.CheckImage()
    ohno.CheckImage()
    play.CheckImage()
    prove.CheckImage()
    pvp.CheckImage()
    pvpvick.CheckImage()
    quest.CheckImage()
    rerun.CheckImage()
    startraid.CheckImage()